building makefile

diff --git a/0x1C-makefiles/100-Makefile b/0x1C-makefiles/100-Makefile
--- a/0x1C-makefiles/100-Makefile
+++ b/0x1C-makefiles/100-Makefile
@@ -26,3 +26,15 @@ oclean:
 fclean: clean oclean
 
 re: fclean all
+
+main.o: main.c m.h
+	@if [ ! -e m.h ]; then \
+		echo "Error: m.h header file is missing"; \
+		exit 1; \
+	fi
+
+school.o: school.c m.h
+	@if [ ! -e m.h ]; then \
+		echo "Error: m.h header file is missing"; \
+		exit 1; \
+	fi
